#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# FORCE A NEW BACKUP
#=================================================
ynh_script_progression --message="Forcing a new backup..." --weight=9

ynh_exec_warn nice -n10 "$install_dir/archivist.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Execution completed" --last
